name = "flan"
version = "0.5.0"
license = "MIT"
author = "Sergio Ibarra-Espinosa"
maintainer = "zergioibarra@gmail.com"
copyright = "Copyright 2025, Sergio Ibarra-Espinosa"
description = "A simple kalman filter."
dependencies.openmp = "*"
dependencies.netcdf = "*"
dependencies.blas = "*"
dependencies.stdlib =  { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm"}

dependencies.csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }

[library]


[executable]
name = "hpc_package"
source-dir = "app"
main = "main.f90"

[[test]]
name = "check"
source-dir = "test"
main = "check.f90"

[[test]]
name = "test_write"
source-dir = "test"
main = "test_write.f90"
